### ISSUE TITLE
d3r nesting order for SearchTree widget

### ISSUE THREAD

**Issue by yonicd** [timelyportfolio/SearchTree#2]
```r
#Doesnt give the value column in the leaves when branch fully grown
Titanic%>%as.data.frame

#Does give the value column in the leaves when branch fully grown
Titanic%>%data.frame%>%mutate(value=NA)%>%distinct

#Current Call
  #d3_nest doesnt nest in the correct order for ggtree.js making the links float to the last open parent
ggtree(
  list(
    root = d3r::d3_nest(
      Titanic%>%data.frame%>%mutate(value=NA)%>%distinct,
      value_cols = "Freq"
    ),
    layout = "collapse"
  ),
  name = "id",
  value = "colname"
)

#Call with old df2tree function
  #df2tree nests in the correct order for ggtree.js giving a unique parent for each child
ggtree(
  list(
    root=df2tree(Titanic%>%data.frame%>%mutate(value=NA)%>%distinct),
    layout = "collapse"
  ),
  name = "name",
  value = "value"
)

#Compare different nesting orders visually
jsonedit(d3r::d3_nest(
  Titanic%>%data.frame%>%mutate(value=NA)%>%distinct,
  value_cols = "Freq",
  json = F
))

jsonedit(df2tree(Titanic%>%data.frame%>%mutate(value=NA)%>%distinct))
```

**Comment by timelyportfolio** [comment]
These [lines](https://github.com/timelyportfolio/SearchTree/blob/master/inst/htmlwidgets/ggtree.js#L91-L92) are the source of the trouble.  The easy (but not sure best) is to use a key other than `id` which is very common in d3 hierarchies and does not always imply uniqueness.  I will pursue this solution first and think more on a better and more robust solution.

**Comment by timelyportfolio** [comment]
still need to fix https://github.com/timelyportfolio/d3r/issues/9 but closer

**Comment by yonicd** [comment]
The mapping looks unique now. It looks like the final leaf (Freq) is not being shown. Using df3tree I used a (bad) work around to force it to show by adding another empty column to the end of the df structure. How would I do this using d3_nest?

I've had many cases that the difference in branches only comes out in the final leaf. When the purpose is converting to query strings that is an important distinction.

**Comment by yonicd** [comment]
answered my own question:

```r
ggtree(
     list(
         root = d3r::d3_nest(
             Titanic%>%data.frame%>%mutate(value=NA)%>%distinct,
             value_cols = "value" #<== change from Freq to value
         ),
         layout = "collapse"
     ),
     name = "id",
     value = "colname"
)
```

**Comment by timelyportfolio** [comment]
yep, completely rethinking my `d3_nest` now.  Will work there for a while and hopefully come up with a better solution.

**Comment by timelyportfolio** [comment]
@yonicd, with the newest changes to `d3r`, you can now do:

```
ggtree(
    list(
        root = d3r::d3_nest(
            Titanic%>%data.frame
        ),
        layout = "collapse"
    ),
    value = "colname"
)
```

**Comment by timelyportfolio** [comment]
With https://github.com/timelyportfolio/d3r/commit/ddc94dc3ce488c2df358ecaf0548410300b4e8ae, I will change `uniqueid` back to `id`.  I looked around at a bunch of other examples, and I think the pattern Mike Bostock and other have set assumes `id` will be unique.

**Comment by yonicd** [comment]
that works. it is an easier call also wo naming the value_cols (in searchtree case the selectize order sets the hierarchy for ggtree).

if it is returned to `id` will the mapping remain unique?

**Comment by timelyportfolio** [comment]
Yes, I just pushed the change.  I believe it works as expected.

**Comment by yonicd** [comment]
works good now. thanks
