### ISSUE TITLE
make the R version requirement >3.2.0 in the description file 

### ISSUE THREAD

**Issue by yonicd** [timelyportfolio/SearchTree#3]
Our servers are still running older R versions (3.2.3) 

I dont think it should make much difference to the widget for it to be from 3.2.0

**Comment by timelyportfolio** [comment]
The whole DESCRIPTION is just the base from `devtools` and requires full rework.  Do you want to change the name from `ggtree`?  This will definitely work in 3.2.0.

**Comment by yonicd** [comment]
can we try it?

**Comment by timelyportfolio** [comment]
3.2?

**Comment by yonicd** [comment]
yes
