### ISSUE TITLE
missing colname

### ISSUE THREAD

**Issue by yonicd** [timelyportfolio/SearchTree#4]
```r
ggtree(
  list(
    root = d3r::d3_nest(
      Titanic%>%data.frame%>%mutate(value=NA)%>%distinct,
    ),
    layout = "collapse"
  ),
  name="name"
)
```

**Comment by timelyportfolio** [comment]
Does this help https://github.com/timelyportfolio/SearchTree/blob/master/inst/examples/titanic_example.R?

**Comment by yonicd** [comment]
yes

**Comment by timelyportfolio** [comment]
In general in most `d3` tree graphs, `value` represents the size.  This implementation is a little confusing since the value is the colname.  Hope that makes you feel better :)  We can change however you would like.
